DROP TABLE IF EXISTS CovidStatistics; 
CREATE TABLE CovidStatistics(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
KeyId VARCHAR(100) NOT NULL ,
Country VARCHAR(50) NOT NULL,
Province VARCHAR(50),
City VARCHAR(50), 
Confirmed INT NOT NULL,
Deaths INT NOT NULL,
Recovered INT,
LastUpdate VARCHAR(100) NOT NULL
);    